spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spcha?autoReconnect=true&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&noAccessToProcedureBodies=true&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
